# BOSH deployment name - anything you want
deployment_name: prometheus

# REQUIRED: OpsManager URL and credentials
pcf_opsman_admin_username:
pcf_opsman_admin_password:
opsman_url:

# OPTIONAL: if you need to use a jumphost to connect to a BOSH Director, provide these details
# (it is often the OpsManager VM)
jumpbox_url:
jumpbox_port:
jumpbox_username:
jumpbox_ssh_key:

# REQUIRED: Set to either opsman_bosh or external_bosh. If set to "opsman_bosh", Prometheus deployment will be created with the BOSH Director managed by OpsMan.
# If set to "external_bosh", Prometheus deployment will be created in whatever BOSH Director you specify with external_bosh_properties below.
director_for_deployment: opsman_bosh

# REQUIRED ONLY IF director_for_deployment is set to "external_bosh", otherwise leave empty.
external_bosh_address:
external_bosh_client:
external_bosh_client_secret:
external_bosh_ca_cert:

# set to something very secure! you won't need to use these passwords at all
uaa_clients_firehose_exporter_secret:
uaa_clients_cf_exporter_secret:
uaa_bosh_exporter_client_secret:

# REQUIRED: This will be the admin password to log in to Grafana GUI
grafana_admin_password:
# REQUIRED: This will be the admin password to log in to Prometheus GUI
prometheus_admin_password:
# REQUIRED: This will be the admin password to log in to Alertmanager GUI
alertmanager_password:

# REQUIRED: AZ(s) for the deployment (must match BOSH Director configuration)
deploy_azs: [europe-west1-d]
# REQUIRED: network for the deployment (must match BOSH Director configuration)
deploy_network: [{name: pcf-net}]

# OPTIONAL but RECOMMENDED: Github token to authenticate with Github. You can generate one at https://github.com/settings/tokens
# If left empty, you will quickly exhaust the Github API calls limits.
github_token:

#
# Parameters below are fine if you are just kicking tires
#

# These values work for a small deployment on PCF. Change to adjust resources
deploy_vm_type_micro: micro
deploy_vm_type_small: small

# arbitrary name for this environment (eg. 'prod')
metrics_environment: pcf

skip_ssl_verify: true
